name: build-and-deploy-jekyll-site

on:
  push:
    branches:
      - master # or main after October 2020

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        with:
          target_branch: "gh-pages"
        env:
          JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
          JEKYLL_ENV: production
